version: '3'

services:

  temperature:
    image: pluspeterpublic/temperature:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  windspeed:
      image: pluspeterpublic/windspeed:latest
      ports:
        - "8080:8080"
      environment:
        - PORT=8080
      restart: unless-stopped

  web:
    build: .
    command: python3 manage.py runserver
    ports:
        - "8001:8001"
      environment:
        - PORT=8001
    volumes:
      - .:/app
    depends_on:
      - temperature
      - windspeed
